### ISSUE TITLE
Can't add fields in data types after a data reference field is added

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#43]
**Repro**:

1. Create a dynamic data type
2. Add a field of the Data Reference type.
3. Try and add another field.

**Expected**: You can add another field
**Actual**: An error pops up: "FormatException. Input string was not in a correct format."

**Note**: Affected are all kinds: global, page data folder and meta types

--- LOG ---

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at CompositeTypeFieldDesigner.TypeFieldDesigner.get_CanAppearInDataRoute()
   at ASP.composite_controls_formscontrols_formuicontroltemplates_developertools_typefielddesigner_ascx.__DataBindingplhDataUrl(Object sender, EventArgs e)
   at System.Web.UI.Control.OnDataBinding(EventArgs e)
   at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
   at System.Web.UI.Control.DataBind()
   at CompositeTypeFieldDesigner.TypeFieldDesigner.InitializeDetailsSplitPanel()
   at CompositeTypeFieldDesigner.TypeFieldDesigner.Field_Select(Guid fieldId)
   at CompositeTypeFieldDesigner.TypeFieldDesigner.AddNewButton_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by wwwysocki** [comment]
Still active if selecting these built-in data types for the Reference field:

* C1 Image
* C1 Media File
* C1 Media Folder

(C1 Page and custom data types seem OK now)
